-- Ampliar el ENUM operation_type con todos los tipos del catálogo
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'BUY_FIAT';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'BUY_CRYPTO';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'AIRDROP';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'STAKING_REWARD';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'MINING_REWARD';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'LENDING_INTEREST';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'CASHBACK';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'FORK';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'SELL_FIAT';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'SELL_CRYPTO';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'GIFT_SENT';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'LOST';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'TRANSFER_INTERNAL';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'FEE_NETWORK';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'FEE_EXCHANGE';

-- Añadir campo fiscal_treatment a transactions
ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS fiscal_treatment TEXT,
  ADD COLUMN IF NOT EXISTS fifo_effect TEXT,
  ADD COLUMN IF NOT EXISTS catalog_type TEXT;  -- ID del catálogo usado
