-- B6: LAUNCHPOOL_LOCK / LAUNCHPOOL_UNLOCK para Launchpool Subscription/Redemption
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'LAUNCHPOOL_LOCK'   AFTER 'STAKING_UNLOCK';
ALTER TYPE operation_type ADD VALUE IF NOT EXISTS 'LAUNCHPOOL_UNLOCK' AFTER 'LAUNCHPOOL_LOCK';
