import type { OperationType } from './types';

export const ACQUISITION_OPERATIONS: OperationType[] = [
  {
    id: 'BUY_FIAT',
    category: 'ACQUISITION',
    label: 'Compra con EUR',
    description: 'Compra de criptoactivo pagando con euros',
    helper: 'Usa este tipo cuando compras una cripto directamente con euros. El precio historico se consulta automaticamente de Binance si no lo introduces.',
    fiscalHelper: 'No genera evento fiscal en el momento de la compra. El lote FIFO queda abierto hasta que vendas o intercambies el activo.',
    fiscalTreatment: 'NO_TAXABLE_EVENT',
    fifoEffect: 'OPEN_LOT',
    badge: 'Sin efecto fiscal',
    badgeColor: 'gray',
    example: 'Compra 100 XRP a 1.20 EUR/unidad pagando 120 EUR',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',           required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo comprado',        required: true,  type: 'asset',   placeholder: 'XRP, BTC, ETH...' },
      { name: 'amount',      label: 'Cantidad recibida',      required: true,  type: 'number',  placeholder: '100' },
      { name: 'cost_amount', label: 'EUR pagados',            required: false, type: 'number',  hint: 'Opcional. Si no se introduce se calcula con el precio historico de Binance', auto: true },
      { name: 'price_eur',   label: 'Precio unitario EUR',    required: false, type: 'number',  hint: 'Opcional. Se consulta automaticamente de Binance', auto: true },
      { name: 'fee_asset',   label: 'Activo de la fee',       required: false, type: 'asset' },
      { name: 'fee_amount',  label: 'Cantidad de fee',        required: false, type: 'number' },
      { name: 'from_wallet', label: 'Wallet',                 required: true,  type: 'wallet' },
      { name: 'exchange',    label: 'Exchange / Plataforma',  required: false, type: 'text',    placeholder: 'Binance, Kraken...' },
      { name: 'tx_hash',     label: 'Hash de transaccion',    required: false, type: 'text' },
      { name: 'notes',       label: 'Notas',                  required: false, type: 'text' },
    ],
  },

  {
    id: 'BUY_CRYPTO',
    category: 'ACQUISITION',
    label: 'Compra con criptoactivo',
    description: 'Compra pagando con otra cripto o stablecoin (permuta)',
    helper: 'Usa este tipo cuando compras una cripto pagando con otra. Es una permuta fiscal en Espana.',
    fiscalHelper: 'GENERA EVENTO FISCAL. Al entregar el activo pagado se considera una venta al precio de mercado. Se calcula G/P del activo entregado.',
    fiscalTreatment: 'CAPITAL_GAIN_LOSS',
    fifoEffect: 'OPEN_AND_CLOSE_LOT',
    badge: 'G/P Patrimonial',
    badgeColor: 'red',
    example: 'Compra 100 XRP pagando 120 USDC',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',                    required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo recibido',                 required: true,  type: 'asset',   placeholder: 'XRP, BTC...' },
      { name: 'amount',      label: 'Cantidad recibida',               required: true,  type: 'number' },
      { name: 'cost_asset',  label: 'Activo entregado',                required: true,  type: 'asset',   placeholder: 'USDC, BTC...' },
      { name: 'cost_amount', label: 'Cantidad entregada',              required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR del activo entregado', required: false, type: 'number',  hint: 'Opcional. Se consulta automaticamente de Binance', auto: true },
      { name: 'fee_asset',   label: 'Activo de la fee',                required: false, type: 'asset' },
      { name: 'fee_amount',  label: 'Cantidad de fee',                 required: false, type: 'number' },
      { name: 'from_wallet', label: 'Wallet',                          required: true,  type: 'wallet' },
      { name: 'exchange',    label: 'Exchange',                        required: false, type: 'text' },
      { name: 'tx_hash',     label: 'Hash de transaccion',             required: false, type: 'text' },
      { name: 'notes',       label: 'Notas',                           required: false, type: 'text' },
    ],
  },

  {
    id: 'AIRDROP',
    category: 'ACQUISITION',
    label: 'Airdrop',
    description: 'Recepcion gratuita de tokens',
    helper: 'Tokens recibidos gratuitamente. El precio historico se consulta automaticamente.',
    fiscalHelper: 'Criterio prudente Hacienda Espana: rendimiento del capital mobiliario por el valor de mercado en el momento de recepcion.',
    fiscalTreatment: 'CAPITAL_INCOME',
    fifoEffect: 'OPEN_LOT',
    badge: 'Rendimiento Cap. Mob.',
    badgeColor: 'amber',
    example: 'Recibes 1000 tokens de un proyecto nuevo',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora de recepcion', required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Token recibido',            required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad recibida',         required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR en el momento',  required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente de Binance', auto: true },
      { name: 'from_wallet', label: 'Wallet de recepcion',       required: true,  type: 'wallet' },
      { name: 'tx_hash',     label: 'Hash de transaccion',       required: false, type: 'text',   hint: 'Recomendado para justificar ante Hacienda' },
      { name: 'notes',       label: 'Notas / Nombre del proyecto', required: false, type: 'text' },
    ],
  },

  {
    id: 'FORK',
    category: 'ACQUISITION',
    label: 'Fork / Hard Fork',
    description: 'Recepcion de tokens por fork de una blockchain',
    helper: 'Tokens recibidos por un fork. El coste de adquisicion se registra como 0.',
    fiscalHelper: 'Hacienda Espana: coste de adquisicion 0. Cuando vendas, el 100% del precio sera ganancia patrimonial.',
    fiscalTreatment: 'COST_BASIS_ZERO',
    fifoEffect: 'OPEN_LOT',
    badge: 'Coste base 0',
    badgeColor: 'amber',
    example: 'Recibes 1 BCH por tener 1 BTC en el momento del fork',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora del fork', required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Token recibido',        required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad recibida',     required: true,  type: 'number' },
      { name: 'from_wallet', label: 'Wallet',                required: true,  type: 'wallet' },
      { name: 'tx_hash',     label: 'Hash de transaccion',   required: false, type: 'text' },
      { name: 'notes',       label: 'Nombre del fork',       required: false, type: 'text' },
    ],
  },
];
