import type { OperationType } from './types';

export const DISPOSITION_OPERATIONS: OperationType[] = [
  {
    id: 'SELL_FIAT',
    category: 'DISPOSITION',
    label: 'Venta a EUR',
    description: 'Venta de criptoactivo recibiendo euros',
    helper: 'Venta a EUR. Si no introduces los EUR recibidos, se calcula con el precio historico de Binance.',
    fiscalHelper: 'Hacienda Espana: ganancia o perdida patrimonial (base del ahorro IRPF). Se calcula precio venta menos coste FIFO.',
    fiscalTreatment: 'CAPITAL_GAIN_LOSS',
    fifoEffect: 'CLOSE_LOT',
    badge: 'G/P Patrimonial',
    badgeColor: 'red',
    example: 'Vendes 100 XRP a 2 EUR recibiendo 200 EUR',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',        required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo vendido',      required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad vendida',    required: true,  type: 'number' },
      { name: 'cost_amount', label: 'EUR recibidos',       required: false, type: 'number', hint: 'Opcional. Se calcula con el precio historico de Binance', auto: true },
      { name: 'price_eur',   label: 'Precio unitario EUR', required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente', auto: true },
      { name: 'fee_asset',   label: 'Activo de la fee',    required: false, type: 'asset' },
      { name: 'fee_amount',  label: 'Cantidad de fee',     required: false, type: 'number', hint: 'Deducible del precio de venta' },
      { name: 'from_wallet', label: 'Wallet',              required: true,  type: 'wallet' },
      { name: 'exchange',    label: 'Exchange',            required: false, type: 'text' },
      { name: 'tx_hash',     label: 'Hash de transaccion', required: false, type: 'text' },
      { name: 'notes',       label: 'Notas',               required: false, type: 'text' },
    ],
  },

  {
    id: 'SELL_CRYPTO',
    category: 'DISPOSITION',
    label: 'Venta a criptoactivo',
    description: 'Intercambio de una cripto por otra (permuta)',
    helper: 'Intercambio entre criptos. Genera evento fiscal por el activo entregado.',
    fiscalHelper: 'Hacienda Espana: G/P patrimonial por el activo entregado al precio de mercado en el momento del intercambio.',
    fiscalTreatment: 'CAPITAL_GAIN_LOSS',
    fifoEffect: 'OPEN_AND_CLOSE_LOT',
    badge: 'G/P Patrimonial',
    badgeColor: 'red',
    example: 'Intercambias 0.01 BTC por 600 XRP',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',                    required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo entregado',                required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad entregada',              required: true,  type: 'number' },
      { name: 'cost_asset',  label: 'Activo recibido',                 required: true,  type: 'asset' },
      { name: 'cost_amount', label: 'Cantidad recibida',               required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR del activo entregado', required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente', auto: true },
      { name: 'fee_asset',   label: 'Activo de la fee',                required: false, type: 'asset' },
      { name: 'fee_amount',  label: 'Cantidad de fee',                 required: false, type: 'number' },
      { name: 'from_wallet', label: 'Wallet',                          required: true,  type: 'wallet' },
      { name: 'exchange',    label: 'Exchange',                        required: false, type: 'text' },
      { name: 'tx_hash',     label: 'Hash de transaccion',             required: false, type: 'text' },
      { name: 'notes',       label: 'Notas',                           required: false, type: 'text' },
    ],
  },

  {
    id: 'GIFT_SENT',
    category: 'DISPOSITION',
    label: 'Donacion enviada',
    description: 'Envio gratuito de cripto a otra persona',
    helper: 'Envio sin contraprestacion. Genera evento fiscal aunque no recibas dinero.',
    fiscalHelper: 'Hacienda Espana: transmision a titulo lucrativo. El donante tributa por la diferencia entre valor de mercado y coste FIFO.',
    fiscalTreatment: 'CAPITAL_GAIN_LOSS',
    fifoEffect: 'CLOSE_LOT',
    badge: 'G/P Patrimonial',
    badgeColor: 'red',
    example: 'Regalas 100 XRP a un amigo',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',                required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo donado',               required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad donada',             required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR en el momento',    required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente', auto: true },
      { name: 'from_wallet', label: 'Wallet',                      required: true,  type: 'wallet' },
      { name: 'tx_hash',     label: 'Hash de transaccion',         required: false, type: 'text',   hint: 'Muy recomendado para justificar ante Hacienda' },
      { name: 'notes',       label: 'Notas / Destinatario',        required: false, type: 'text' },
    ],
  },

  {
    id: 'LOST',
    category: 'DISPOSITION',
    label: 'Perdida / Robo',
    description: 'Perdida de acceso a fondos o robo',
    helper: 'Perdida de fondos por robo o perdida de clave. Requiere documentacion para Hacienda.',
    fiscalHelper: 'Hacienda Espana: perdida patrimonial deducible si se puede acreditar con pruebas documentales.',
    fiscalTreatment: 'CAPITAL_GAIN_LOSS',
    fifoEffect: 'REDUCE_LOT',
    badge: 'Perdida Patrimonial',
    badgeColor: 'red',
    example: 'Pierdes acceso a una wallet con 500 XRP',
    fields: [
      { name: 'timestamp',   label: 'Fecha aproximada',                    required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo perdido',                      required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad perdida',                    required: true,  type: 'number' },
      { name: 'from_wallet', label: 'Wallet afectada',                     required: true,  type: 'wallet' },
      { name: 'tx_hash',     label: 'Ultima tx conocida',                  required: false, type: 'text' },
      { name: 'notes',       label: 'Descripcion / Referencia denuncia',   required: false, type: 'text', hint: 'Importante documentar para Hacienda' },
    ],
  },
];
