import type { OperationType } from './types';

export const INCOME_OPERATIONS: OperationType[] = [
  {
    id: 'STAKING_REWARD',
    category: 'INCOME',
    label: 'Recompensa de Staking',
    description: 'Tokens recibidos por hacer staking',
    helper: 'Recompensas de staking. El precio historico se consulta automaticamente de Binance.',
    fiscalHelper: 'Hacienda Espana: rendimiento del capital mobiliario. Se tributa en el ano de recepcion por el valor de mercado.',
    fiscalTreatment: 'CAPITAL_INCOME',
    fifoEffect: 'OPEN_LOT',
    badge: 'Rendimiento Cap. Mob.',
    badgeColor: 'amber',
    example: 'Recibes 0.5 ETH de staking rewards',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',          required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Token recibido',        required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad recibida',     required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR',            required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente de Binance', auto: true },
      { name: 'from_wallet', label: 'Plataforma / Wallet',   required: true,  type: 'wallet' },
      { name: 'exchange',    label: 'Plataforma de staking', required: false, type: 'text',   placeholder: 'Binance, Lido...' },
      { name: 'tx_hash',     label: 'Hash de transaccion',   required: false, type: 'text' },
      { name: 'notes',       label: 'Notas',                 required: false, type: 'text' },
    ],
  },

  {
    id: 'MINING_REWARD',
    category: 'INCOME',
    label: 'Recompensa de Mineria',
    description: 'Tokens recibidos por mineria',
    helper: 'Recompensas de mineria. El precio historico se consulta automaticamente.',
    fiscalHelper: 'Hacienda Espana: si la mineria es habitual, rendimiento de actividad economica (base general). Si es ocasional, rendimiento del capital mobiliario.',
    fiscalTreatment: 'GENERAL_INCOME',
    fifoEffect: 'OPEN_LOT',
    badge: 'Actividad Economica',
    badgeColor: 'red',
    example: 'Minas 0.001 BTC',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',        required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Token minado',        required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad recibida',   required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR',          required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente', auto: true },
      { name: 'from_wallet', label: 'Wallet',              required: true,  type: 'wallet' },
      { name: 'tx_hash',     label: 'Hash de transaccion', required: false, type: 'text' },
      { name: 'notes',       label: 'Notas',               required: false, type: 'text' },
    ],
  },

  {
    id: 'LENDING_INTEREST',
    category: 'INCOME',
    label: 'Interes de Lending (flexible)',
    description: 'Intereses recibidos por prestar criptoactivos en producto flexible',
    helper: 'Intereses de plataformas de lending. El precio historico se consulta automaticamente.',
    fiscalHelper: 'Hacienda Espana: rendimiento del capital mobiliario (art. 25.2 LIRPF).',
    fiscalTreatment: 'CAPITAL_INCOME',
    fifoEffect: 'OPEN_LOT',
    badge: 'Rendimiento Cap. Mob.',
    badgeColor: 'amber',
    example: 'Recibes 10 USDC de intereses de Binance Simple Earn Flexible',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',     required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Token recibido',   required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad',         required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR',       required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente', auto: true },
      { name: 'from_wallet', label: 'Wallet',           required: true,  type: 'wallet' },
      { name: 'exchange',    label: 'Plataforma',       required: false, type: 'text' },
      { name: 'notes',       label: 'Notas',            required: false, type: 'text' },
    ],
  },

  {
    id: 'LENDING_INTEREST_LOCKED',
    category: 'INCOME',
    label: 'Interes de Lending (bloqueado)',
    description: 'Intereses recibidos por prestar criptoactivos en producto de plazo fijo',
    helper: 'Intereses de depósitos bloqueados (locked). El precio historico se consulta automaticamente.',
    fiscalHelper: 'Hacienda Espana: rendimiento del capital mobiliario (art. 25.2 LIRPF).',
    fiscalTreatment: 'CAPITAL_INCOME',
    fifoEffect: 'OPEN_LOT',
    badge: 'Rendimiento Cap. Mob.',
    badgeColor: 'amber',
    example: 'Recibes 10 SOL de intereses de Binance Simple Earn Locked',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',     required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Token recibido',   required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad',         required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR',       required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente', auto: true },
      { name: 'from_wallet', label: 'Wallet',           required: true,  type: 'wallet' },
      { name: 'exchange',    label: 'Plataforma',       required: false, type: 'text' },
      { name: 'notes',       label: 'Notas',            required: false, type: 'text' },
    ],
  },

  {
    id: 'CASHBACK',
    category: 'INCOME',
    label: 'Cashback / Bonus',
    description: 'Recompensa en cripto por uso de tarjeta, referidos o promociones',
    helper: 'Cashbacks y bonos en cripto. El precio historico se consulta automaticamente.',
    fiscalHelper: 'Hacienda Espana: rendimiento del capital mobiliario.',
    fiscalTreatment: 'CAPITAL_INCOME',
    fifoEffect: 'OPEN_LOT',
    badge: 'Rendimiento Cap. Mob.',
    badgeColor: 'amber',
    example: 'Recibes 5 EUR en CRO como cashback',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',             required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Token recibido',           required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad',                 required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR',               required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente', auto: true },
      { name: 'from_wallet', label: 'Wallet',                   required: true,  type: 'wallet' },
      { name: 'exchange',    label: 'Plataforma',               required: false, type: 'text' },
      { name: 'notes',       label: 'Descripcion del bonus',    required: false, type: 'text' },
    ],
  },
];
