import type { OperationType } from './types';

export const MOVEMENT_OPERATIONS: OperationType[] = [
  {
    id: 'DEPOSIT_FIAT',
    category: 'MOVEMENT',
    label: 'Depósito EUR',
    description: 'Ingreso de euros desde cuenta bancaria al exchange',
    helper: 'Usa este tipo cuando transfieres euros desde tu banco a un exchange o plataforma. No genera evento fiscal.',
    fiscalHelper: 'Hacienda España: sin efecto fiscal. Solo mueve fiat de tu cuenta bancaria al exchange.',
    fiscalTreatment: 'NO_TAXABLE_EVENT',
    fifoEffect: 'NO_EFFECT',
    badge: 'Sin efecto fiscal',
    badgeColor: 'gray',
    example: 'Transferes 1.000 EUR desde tu banco a Binance',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',         required: true,  type: 'datetime' },
      { name: 'cost_amount', label: 'Importe EUR',          required: true,  type: 'number',  placeholder: '1000' },
      { name: 'from_wallet', label: 'Exchange / Plataforma', required: true,  type: 'wallet' },
      { name: 'notes',       label: 'Notas / Referencia',   required: false, type: 'text' },
    ],
  },

  {
    id: 'DEPOSIT_CRYPTO',
    category: 'MOVEMENT',
    label: 'Depósito cripto',
    description: 'Recepción de cripto desde wallet externa propia',
    helper: 'Usa este tipo cuando recibes cripto desde una wallet tuya no rastreada (hardware wallet, otra plataforma). Se crea un nuevo lote FIFO con el precio histórico como coste de adquisición.',
    fiscalHelper: 'Hacienda España: sin evento fiscal si es un movimiento entre wallets propias. El coste de adquisición original debería transferirse, pero al no poder trazarlo se usa el precio histórico.',
    fiscalTreatment: 'NO_TAXABLE_EVENT',
    fifoEffect: 'OPEN_LOT',
    badge: 'Sin efecto fiscal',
    badgeColor: 'gray',
    example: 'Envías 0.5 BTC desde tu Ledger a Binance',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',           required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo recibido',        required: true,  type: 'asset',  placeholder: 'BTC, ETH, XRP...' },
      { name: 'amount',      label: 'Cantidad recibida',      required: true,  type: 'number' },
      { name: 'price_eur',   label: 'Precio EUR en el momento', required: false, type: 'number', hint: 'Opcional. Se consulta automaticamente de Binance', auto: true },
      { name: 'from_wallet', label: 'Wallet destino',         required: true,  type: 'wallet' },
      { name: 'tx_hash',     label: 'Hash de transaccion',    required: false, type: 'text',   hint: 'Recomendado para trazabilidad' },
      { name: 'notes',       label: 'Notas / Origen',         required: false, type: 'text' },
    ],
  },

  {
    id: 'WITHDRAW',
    category: 'MOVEMENT',
    label: 'Retirada cripto',
    description: 'Envío de cripto a wallet externa propia',
    helper: 'Usa este tipo cuando envías cripto a una wallet tuya no rastreada (hardware wallet, otra plataforma). El lote FIFO se reduce pero no se genera ganancia/pérdida si es tu propia wallet.',
    fiscalHelper: 'Hacienda España: sin evento fiscal si es un movimiento entre wallets propias. Si el destinatario es un tercero, puede generar una transmisión lucrativa sujeta a G/P patrimonial.',
    fiscalTreatment: 'NO_TAXABLE_EVENT',
    fifoEffect: 'REDUCE_LOT',
    badge: 'Sin efecto fiscal',
    badgeColor: 'gray',
    example: 'Envías 0.5 BTC de Binance a tu Ledger',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',           required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo enviado',         required: true,  type: 'asset',  placeholder: 'BTC, ETH, XRP...' },
      { name: 'amount',      label: 'Cantidad enviada',       required: true,  type: 'number' },
      { name: 'from_wallet', label: 'Wallet origen',          required: true,  type: 'wallet' },
      { name: 'fee_asset',   label: 'Activo de la fee de red', required: false, type: 'asset' },
      { name: 'fee_amount',  label: 'Fee de red',             required: false, type: 'number' },
      { name: 'tx_hash',     label: 'Hash de transaccion',    required: false, type: 'text',   hint: 'Recomendado para trazabilidad' },
      { name: 'notes',       label: 'Notas / Destino',        required: false, type: 'text' },
    ],
  },

  {
    id: 'WITHDRAW_FIAT',
    category: 'MOVEMENT',
    label: 'Retirada EUR',
    description: 'Retirada de euros del exchange a cuenta bancaria',
    helper: 'Usa este tipo cuando retiras euros desde un exchange o plataforma a tu banco. No genera evento fiscal.',
    fiscalHelper: 'Hacienda España: sin efecto fiscal. Solo mueve fiat del exchange de vuelta a tu cuenta bancaria.',
    fiscalTreatment: 'NO_TAXABLE_EVENT',
    fifoEffect: 'NO_EFFECT',
    badge: 'Sin efecto fiscal',
    badgeColor: 'gray',
    example: 'Retiras 500 EUR de Binance a tu banco',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',         required: true,  type: 'datetime' },
      { name: 'cost_amount', label: 'Importe EUR',          required: true,  type: 'number',  placeholder: '500' },
      { name: 'from_wallet', label: 'Exchange / Plataforma', required: true,  type: 'wallet' },
      { name: 'notes',       label: 'Notas / Referencia',   required: false, type: 'text' },
    ],
  },

  {
    id: 'TRANSFER_INTERNAL',
    category: 'MOVEMENT',
    label: 'Transferencia interna',
    description: 'Movimiento entre wallets propias',
    helper: 'Transferencia entre wallets tuyas. Sin evento fiscal. El lote FIFO mantiene su coste original.',
    fiscalHelper: 'Hacienda Espana: sin efecto fiscal. No hay cambio de titular.',
    fiscalTreatment: 'NO_TAXABLE_EVENT',
    fifoEffect: 'MOVE_LOT',
    badge: 'Sin efecto fiscal',
    badgeColor: 'gray',
    example: 'Envias 500 XRP de Binance a tu Tangem',
    fields: [
      { name: 'timestamp',   label: 'Fecha y hora',                            required: true,  type: 'datetime' },
      { name: 'asset',       label: 'Activo transferido',                      required: true,  type: 'asset' },
      { name: 'amount',      label: 'Cantidad enviada (incluyendo fee de red)', required: true,  type: 'number' },
      { name: 'from_wallet', label: 'Wallet origen',                           required: true,  type: 'wallet' },
      { name: 'to_wallet',   label: 'Wallet destino',                          required: true,  type: 'wallet' },
      { name: 'fee_asset',   label: 'Activo de la fee de red',                 required: false, type: 'asset' },
      { name: 'fee_amount',  label: 'Fee de red',                              required: false, type: 'number' },
      { name: 'tx_hash',     label: 'Hash de transaccion on-chain',            required: false, type: 'text',   hint: 'Recomendado para trazabilidad' },
      { name: 'notes',       label: 'Notas',                                   required: false, type: 'text' },
    ],
  },
];
